### ISSUE TITLE
"ancestral_variants does not exist" Problem and Solution

### ISSUE THREAD

**Issue by rnbehm** [schellt/busco2snap#1]
**Problem:**
I was trying to use Busco2Snap (B2S) to convert my outputs from Busco into an hmm that I can use as an input into the Maker Pipeline. 
The program would run for about 3 secounds and then output the error that "ancestral_variants does not exist".
I am using Busco v5.4.3 but I also tried with Busco v5.2.2 since this was the last tested version according to the readme.
I am working on Hymenoptera (wasps) and  so my input for B2S was ~/BuscoOutputFolder/run_hymenoptera_odb10 and from there it could access full_table.tsv and /augustus_output/retraining_parameters which exist in this directory and are needed for starting B2S.
Ancestral_variants does not exist in this directory, but a completely different directory called /busco_downloads/lineages/hymenoptera_odb10 that is generated into the working directory when/where Busco is initially ran.
When moving the ancestral_variants file into the input directory B2S, the same error occured regardless.

**Solution:**
My collaborator (https://github.com/rfitak) and I reviewed the pipeline code for B2S and found the issue on line 468 which is where ancestral_variants is called:

```perl
if(not -l "$out_dir/ancestral_variants"){
	$cmd = "ln -sf $lineage_path/ancestral_variants $out_dir/ancestral_variants";
	exe_cmd($cmd,$verbose,$dry);
``` 

We replaced $lineage_path/ancestral_variants with the actual path to the ancestral_variants file (located in the busco_downloads folder not the output folder).
Once this change occured, B2S was able to run normally and after 03:36:21 the program completed successfully. 

In order to remedy this in the future, since I have a lot of B2S's to run, Bob edited the original pipeline to include a new mandatory variable -database where you set the path of the directory ancestral_variants is located in during the input (the busco lineage database located in the busco_downloads folder). The updated usage appears in the help screen as well.
In my example case,  the <database> variable would be ~/busco_downloads/lineages/hymenoptera_odb10

We found that this was the easiest way to avoid the error and allow for smoother usage. The updated pipeline is attached below and will hopefully help others.

[busco2snapv03.txt](https://github.com/schellt/busco2snap/files/15404185/busco2snapv03.txt)

**Comment by schellt** [comment]
Hi Rachel,
thanks a lot for using busco2snap and for looking into it.
I was always using already downloaded sets, that's why I coded it like this.
Furthermore, I switched to either running BUSCO with metaeuk or running compleasm. In both cases you get a gff file, which specifies the intron/exon boundaries. For older BUSCO versions (<5, I guess), this was not the case and therefore I was creating this script. As well, I was using SNAP models for annotation with MAKER. BRAKER3 is easier to handle and results are very good. As well you can specify a BUSCO lineage to create hints.
So, all in all I don't use this script myself anymore. Feel free to re-open.
Hope that helps.
Best,
Tilman
